version: '3.2'
services:
  nuxt-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/var/www/nuxt
    networks:
      - nuxt-network
networks:
  nuxt-network:
    driver: bridge
